arch: "arm64"
os: "Linux"

images:
  - location: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-arm64.img"
    arch: "arm64"

cpus: 2
memory: "4GiB"
disk: "40GiB"

networks:
  - socketVMNet: "splentnet"
    interface: "lima0"

# Montaje con NFS para que los permisos sean “Linux-like” y no te maree Git.
# Esto es lo más parecido al dmode/fmode del shared folder de VirtualBox.
mounts:
  - location: "."
    mountPoint: "/workspace"
    writable: true
    mountType: "nfs"

ssh:
  forwardAgent: false

# Cloud-init: fija IP 10.10.10.10 dentro del guest
provision:
  - mode: system
    script: |
      set -eux
      cat >/etc/netplan/99-splent.yaml <<'EOF'
      network:
        version: 2
        ethernets:
          lima0:
            dhcp4: no
            addresses: [10.10.10.10/24]
            gateway4: 10.10.10.1
            nameservers:
              addresses: [1.1.1.1, 8.8.8.8]
      EOF
      netplan apply